service: workflow

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  logRetentionInDays: 14
  versionFunctions: true

functions:
  hello:
    handler: src/handler.generateRandomNumber
    timeout: 10
